# Configuration
cnn:
    patch_size: 64
    model_path: checkpoint.pth.tar
    input_channels: 2 # SVF & GLI
    learning_rate: 0.01
    batch_size: 16
    epochs: 30

copernicus-s3:
    access_key: ${oc.env:ACCESS_KEY}
    secret_access_key: ${oc.env:SECRET_ACCESS_KEY}