# Configuration
crs: '25830' # EPSG code

study_period: # Format: DD-MM-YYYY
    start: '01-06-2023'
    end: '31-08-2023'

download:
    copernicus-s3:
        access_key: ${oc.env:ACCESS_KEY}
        secret_access_key: ${oc.env:SECRET_ACCESS_KEY}
    netatmo:
        token: 679b955ca250de0e040eb492|949b82156478188bbb44f8918f7295c3

cnn:
    patch_size: 64
    model_path: checkpoint.pth.tar
    input_channels: 1 # SVF & GLI
    learning_rate: 0.01
    batch_size: 16
    epochs: 30

kriging:
    added_variables_resolution: 100 # m/px; resolution used in the step 'add-raster-values'

temperature:
    quality_control:
        min_temperature: -20 # ºC
        max_temperature: 45 # ºC
        temperature_variation_threshold: 10 # ºC
        lower_tail: -2.32
        upper_tail: 1.64
    reference_stations: [
        '70:ee:50:7a:c2:72',
        '70:ee:50:73:e2:d8',
        '70:ee:50:06:91:04'
    ]
    stations_to_remove: [
        '70:ee:50:2b:2b:98',
        '70:ee:50:b5:0d:9c',
        '70:ee:50:32:af:3e'
    ]

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '[%(asctime)s] %(levelname)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    root:
        level: INFO
        handlers: [console]
    
paths:
    shapefiles:
        folder_name: 'shapefiles'
        study_area: 'study_area.shp'
        netatmo_stations: 'netatmo_stations.shp'
    rasters:
        folder_name: 'rasters'
        sentinel_folder_name: 'sentinel'
        average_prefix: 'average_'
        blue: 'blue.tif'
        green: 'green.tif'
        red: 'red.tif'
        nir: 'nir.tif'
        swir1: 'swir1.tif'
        swir2: 'swir2.tif'
        dsm: 'dsm.tif' # DSM stands for Digital Surface Model
        gli: 'gli.tif' # GLI stands for Green Leaf Index
        nbai: 'nbai.tif' # NBAI stands for Normalized Built-up Area Index
        ndti: 'ndti.tif' # NDTI stands for Normalized Difference Turbidity Index
        ndvi: 'ndvi.tif' # NDVI stands for Normalized Difference Vegetation Index
        svf: 'svf.tif' # SVF stands for Sky View Factor
        stacked_variables: 'stacked_variables.tif' # Stack variables to use for training/predicting with the CNN
        cnn_result: 'cnn_result.tif' # Predicted result by the CNN
        kriging_result: 'kriging_result.tif'
    stations:
        folder_name: 'stations'
        stations: 'netatmo_data.csv' # Includes all Netatmo stations in the study area with their coordinates
        temperatures: 'temperatures.csv' # Includes all recorded temperatures, compiled from the merged CSV files of all stations after data cleaning and quality control
        differences: 'differences.csv' # Includes the computed temperature differences between each station and the reference stations
    cnn:
        patch_folder_name: 'patches'
    kriging:
        folder_name: 'kriging'
