# Configuration
crs: '32633' # EPSG code
#crs: '25830'

study_period: # Format: YYYY-MM-DD
    start: '2023-06-01'
    end: '2023-08-31'

download:
    copernicus-s3:
        access_key: ${oc.env:ACCESS_KEY}
        secret_access_key: ${oc.env:SECRET_ACCESS_KEY}
    netatmo:
        token: 679b955ca250de0e040eb492|ea6c8e77267d80103f62c9027bcbd0d2

cnn:
    patch_size: 64
    model_path: 'src/cnn/checkpoint.pth.tar'
    input_channels: 2 # SVF & GLI
    learning_rate: 0.01
    batch_size: 16
    epochs: 30

kriging:
    added_variables_resolution: 100 # m/px; resolution used in the step 'add-raster-values'

temperature:
    quality_control:
        min_temperature: -20 # ºC
        max_temperature: 45 # ºC
        temperature_variation_threshold: 10 # ºC
        lower_tail: -2.32
        upper_tail: 1.64
    reference_stations: [
        '70:ee:50:73:e9:4c',
        '70:ee:50:37:20:4a',
        '70:ee:50:7a:fa:08',
        '70:ee:50:90:f2:36'
    ]
    stations_to_remove: [
        '70:ee:50:02:02:54', 
        '70:ee:50:14:41:64', 
        '70:ee:50:1f:5f:78',
        #'70:ee:50:37:20:4a', 
        '70:ee:50:5f:3e:28', 
        #'70:ee:50:73:e9:4c',
        '70:ee:50:7b:2c:2c',
        '70:ee:50:2d:0d:e0', # <- Here starts manual removed stations
        '70:ee:50:17:81:ae',
        '70:ee:50:3f:48:04',
        '70:ee:50:14:7f:66',
        '70:ee:50:7f:d2:ac',
        '70:ee:50:3c:ec:0a',
        '70:ee:50:02:02:54',
        '70:ee:50:19:09:54',
        '70:ee:50:17:bd:60', # <- Further selection, removing too close stations
        '70:ee:50:90:76:94',
        '70:ee:50:33:41:8c',
        '70:ee:50:7a:d7:6e',
        '70:ee:50:7f:a6:ec',
        '70:ee:50:28:bc:4c',
        '70:ee:50:19:3e:f6',
        '70:ee:50:9d:15:20',
        '70:ee:50:58:f9:28',
        '70:ee:50:17:66:76',
        '70:ee:50:3e:ec:54',
        '70:ee:50:19:06:30',
        '70:ee:50:17:66:be',
        '70:ee:50:2c:79:00',
        '70:ee:50:1b:20:ba'

    ]

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '[%(asctime)s] %(levelname)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    root:
        level: INFO
        handlers: [console]
    
paths:
    shapefiles:
        folder_name: 'shapefiles'
        study_area: 'study_area.shp'
        netatmo_stations: 'netatmo_stations.shp'
    rasters:
        folder_name: 'rasters'
        sentinel_folder_name: 'sentinel'
        average_prefix: 'average_'
        blue: 'blue.tif'
        green: 'green.tif'
        red: 'red.tif'
        nir: 'nir.tif'
        swir1: 'swir1.tif'
        swir2: 'swir2.tif'
        dsm: 'dsm.tif' # DSM stands for Digital Surface Model
        gli: 'gli.tif' # GLI stands for Green Leaf Index
        nbai: 'nbai.tif' # NBAI stands for Normalized Built-up Area Index
        ndti: 'ndti.tif' # NDTI stands for Normalized Difference Turbidity Index
        ndvi: 'ndvi.tif' # NDVI stands for Normalized Difference Vegetation Index
        svf: 'svf.tif' # SVF stands for Sky View Factor
        stacked_variables: 'stacked_variables.tif' # Stack variables to use for training/predicting with the CNN
        cnn_result: 'cnn_result.tif' # Predicted result by the CNN
        kriging_result: 'kriging_result.tif'
    stations:
        folder_name: 'stations'
        stations: 'netatmo_stations.csv' # Includes all Netatmo stations in the study area with their coordinates
        temperatures: 'temperatures.csv' # Includes all recorded temperatures, compiled from the merged CSV files of all stations after data cleaning and quality control
        differences: 'differences.csv' # Includes the computed temperature differences between each station and the reference stations
    cnn:
        patch_folder_name: 'patches'
    kriging:
        folder_name: 'kriging'
