# Configuration
crs: '25830' # EPSG code

study_period: # Format: DD-MM-YYYY
    start: '01-06-2023'
    end: '31-08-2023'

download:
    copernicus-s3:
        access_key: ${oc.env:ACCESS_KEY}
        secret_access_key: ${oc.env:SECRET_ACCESS_KEY}
    netatmo:
        token: 679b955ca250de0e040eb492|949b82156478188bbb44f8918f7295c3

cnn:
    patch_size: 64
    model_path: checkpoint.pth.tar
    input_channels: 1 # SVF & GLI
    learning_rate: 0.01
    batch_size: 16
    epochs: 30

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '[%(asctime)s] %(levelname)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    root:
        level: INFO
        handlers: [console]
    
paths:
    shapefiles:
        study_area: 'study_area.shp'
        netatmo_stations: 'netatmo_stations.shp'
    rasters:
        folder_name: 'rasters'
        sentinel_folder_name: 'sentinel'
        dsm: 'dsm.tif' # DSM stands for Digital Surface Model
        gli: 'gli.tif' # GLI stands for Green Leaf Index
        svf: 'svf.tif' # SVF stands for Sky View Factor
    stations:
        folder_name: 'stations'
        temperatures: 'temperatures.csv' # Includes all recorded temperatures, compiled from the merged CSV files of all stations after data cleaning and quality control
        differences: 'diffs.csv' # Includes the computed temperature differences between each station and the reference stations
