import pandas as pd
import requests
import os

# Data frame to store date and its average temperature
df = pd.DataFrame(columns=['date', 'avgt'])

# Change the URLs to the ones generated by https://opendata.aemet.es/centrodedescargas/productosAEMET?
urls = [
    'https://opendata.aemet.es/opendata/sh/2010dfd1',
    'https://opendata.aemet.es/opendata/sh/f55f1e54'
]

for url in urls:
    # Sending a GET request to the URL
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse JSON data from the response
        data = response.json()
        for day in data:
            df.loc[len(df.index)] = [day['fecha'], day['tmed'].replace(',', '.')]
    else:
        print(f'Error: Failed to retrieve data. Status code {response.status_code}')

folder = os.path.abspath(os.path.join(os.getcwd(), '../data'))
file_path = folder + '/temperatures.csv'
df.to_csv(file_path, index=False)